version: '3.8'

services:
  photo-server:
    container_name: photo-server1
    image: photo-server1
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3001
    command: npm run start:dev
volumes:
  pgdata: