version: '3.8'

services:
  photo-microservice:
    container_name: photo-microservice1
    image: photo-microservice1
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3002:3002
    command: npm run start:dev

volumes:
  pgdata: